export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT'
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT'
export const EDIT_ASSIGNMENT = 'EDIT_ASSIGNMENT'
export const GET_ASSIGNMENT = 'GET_ASSIGNMENT'
export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS'
